dim program  
program="d:\Program Files (x86)\Tencent\QQPCMgr\11.0.16794.227\Uninst.exe" 
set Wshell=CreateObject("Wscript.Shell")  
set oexec=Wshell.Exec(program) 
wscript.Sleep 1000
Wshell.AppActivate "Uninst.exe"
wscript.Sleep 100 
Wshell.SendKeys "+{TAB}" 
wscript.Sleep 100  
Wshell.SendKeys "+{TAB}" 
wscript.Sleep 100   
Wshell.SendKeys "+{TAB}" 
wscript.Sleep 100  
Wshell.SendKeys "+{TAB}"
wscript.Sleep 100   
Wshell.SendKeys "+{TAB}" 
wscript.Sleep 100 
Wshell.SendKeys "{ENTER}" 
Wshell.SendKeys "+{TAB}" 
wscript.Sleep 100   
Wshell.SendKeys "+{TAB}" 
wscript.Sleep 100  
Wshell.SendKeys "+{TAB}"
wscript.Sleep 100   
Wshell.SendKeys "+{TAB}" 
wscript.Sleep 100 
Wshell.SendKeys "+{TAB}" 
wscript.Sleep 200 
Wshell.SendKeys "{ENTER}" 