json_writer.o : json_writer.cpp 
	clang++ -Wall -c -g json_writer.cpp 
json_reader.o : json_reader.cpp 
	clang++ -Wall -c -g json_reader.cpp 
json_value.o : json_value.cpp 
	clang++ -Wall -c -g json_value.cpp 
clean :
	-rm *.o *~
